#!/bin/bash

num="$NUM"

if [[ -n "$num" && "$num" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
    printf "%.2f\n" "$num"
else
    echo "Environment variable NUM is not set or does not contain a valid number."
fi
